(function(){
  'use strict';
  const K=window.K,O={};K.OverhaulUI=O;
  let game=null,ui=null,modifierRanks={},begin=null,lastMapRevision=-1,padHeld={},lastPad=0,worldHudKey='',portraitTimer=0,lastPadCheck=0,dockEl=null,objectiveEl=null,marketBtnEl=null;
  const esc=s=>String(s===undefined?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const by=id=>document.getElementById(id);
  function screen(id){ui.showScreen(id,id==='screen-market'||id==='screen-world-map');}
  function panel(id,title,content){let host=by(id);if(host)return host;host=document.createElement('div');host.id=id;host.className='screen hidden overhaul-screen';host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.setAttribute('aria-label',title);host.innerHTML='<section class="room-panel wide tall overhaul-panel"><div class="meander thin"></div><h2>'+title+'</h2>'+content+'<div class="meander thin"></div></section>';by('stage').appendChild(host);return host;}
  O.mapModel=function(G){const w=G.world;if(!w)return{cells:[],markers:[]};const s=w.tileSize||80,visited=c=>w.revealed?.[Math.round(c.x/s)+','+Math.round(c.y/s)];return{bounds:w.bounds,tileSize:s,cells:w.cells.filter(visited),markers:w.nodes.filter(n=>n.discovered||visited(n)).concat(w.nodes.some(n=>n.id===w.capstone?.id&&(n.discovered||visited(n)))?[]:w.capstone?[w.capstone]:[]).filter((n,i,a)=>a.findIndex(t=>t.id===n.id)===i),player:G.player};};
  O.bind=function(G,callbacks){
    game=G;ui=callbacks;
    panel('screen-modifiers','SHAPE YOUR DESCENT','<p class="overhaul-intro">Choose the roads and challenges ahead. Every configuration is free. The seed and rules stay fixed until the descent ends.</p><div id="ordinary-modifiers" class="modifier-catalog"></div><div id="modifier-preview" class="overhaul-summary" role="status" aria-live="polite"></div><div class="title-buttons"><button id="modifier-start" class="btn primary">BEGIN DESCENT</button><button id="modifier-clear" class="btn">CLEAR MODIFIERS</button><button id="modifier-back" class="btn ghostly">BACK</button></div>');
    panel('screen-world-map','THE ROADS YOU KNOW','<p id="map-caption" class="overhaul-intro"></p><div id="world-map-drawing" class="world-map-drawing" role="img" aria-label="Explored terrain and known destinations"></div><div id="map-legend" class="map-legend"></div><button id="map-close" class="btn">RETURN TO THE ROAD</button>');
    panel('screen-market','CHARON’S WARES','<p class="overhaul-intro">The docks are safe. Browse here or approach a stall. Stock and prices stay with this crossing.</p><div id="market-balance" class="overhaul-summary" role="status" aria-live="polite"></div><div id="market-inventory" class="market-inventory"></div><div class="title-buttons"><button id="market-close" class="btn">CONTINUE BROWSING (STAY)</button><button id="market-return" class="btn ghostly">LEAVE THE MARKET</button></div>');
    panel('screen-house','THOSE WHO REMEMBER','<p class="overhaul-intro">Promises and unfinished journeys follow you back to the House.</p><div id="house-scenes" class="house-scenes"></div><button id="house-close" class="btn">BACK</button>');
    const dock=document.createElement('div');dock.id='exploration-tools';dock.className='exploration-tools hidden';dock.innerHTML='<span id="world-objective"></span><button id="world-map-button" aria-label="Open explored map">MAP</button><button id="world-market-button" class="hidden">WARES · B</button>';by('stage').appendChild(dock);
    by('world-map-button').addEventListener('click',O.openMap);by('world-market-button').addEventListener('click',O.market);by('map-close').addEventListener('click',()=>screen(null));
    by('modifier-start').addEventListener('click',()=>{if(begin){const fn=begin;begin=null;fn(Object.assign({},modifierRanks));}});
    by('modifier-clear').addEventListener('click',()=>{modifierRanks={};renderModifiers();});by('modifier-back').addEventListener('click',()=>screen('screen-heroes'));
    by('market-close').addEventListener('click',()=>screen(null));by('market-return').addEventListener('click',()=>{G.returnFromMarket();screen(null);ui.updateHUD();});
    by('house-close').addEventListener('click',()=>screen('screen-title'));
    const title=by('btn-begin')?.parentNode;if(title){const b=document.createElement('button');b.id='btn-house-stories';b.className='btn ghostly';b.textContent='CONVERSATIONS';b.addEventListener('click',O.house);title.appendChild(b);}
    if(!G.ctx)O.compatibility(false);
  };
  O.compatibility=function(lost){let box=by('world-compatibility');if(!box){box=document.createElement('div');box.id='world-compatibility';box.setAttribute('role','alert');by('stage').appendChild(box);}box.className='world-compatibility';box.textContent=lost?'The world renderer is recovering. Your descent is paused; resume after graphics return.':'Katabasis needs WebGL to explore its worlds. Enable hardware acceleration and reopen the game in a browser with WebGL support.';};
  O.clearCompatibility=function(){by('world-compatibility')?.remove();};
  O.configure=function(callback){begin=callback;modifierRanks=Object.assign({},K.Save.data.ordinaryModifiers||{});renderModifiers();screen('screen-modifiers');};
  function renderModifiers(){
    const root=by('ordinary-modifiers');root.innerHTML='';
    const catalog=K.RunSystems.MODIFIERS||K.RunSystems.PACTS;
    catalog.forEach(mod=>{const row=document.createElement('label');row.className='modifier-row';row.innerHTML='<span><strong>'+esc(mod.name)+'</strong><small>'+esc(mod.desc||mod.description||'')+'</small></span>';const select=document.createElement('select');select.setAttribute('aria-label',mod.name+' severity');const max=mod.maxRank||mod.max||3;for(let n=0;n<=max;n++){const option=document.createElement('option');option.value=n;option.textContent=n?'Rank '+n:'Off';select.appendChild(option);}select.value=modifierRanks[mod.id]||0;select.addEventListener('change',()=>{const v=Number(select.value);if(v)modifierRanks[mod.id]=v;else delete modifierRanks[mod.id];updateModifierPreview();});row.appendChild(select);root.appendChild(row);});updateModifierPreview();
    if(K.Endgame){const target=document.createElement('label');target.className='modifier-row';target.innerHTML='<span><strong>GEAR PURSUIT</strong><small>Bias eligible endgame finds toward a build family. Every set can still appear.</small></span>';const select=document.createElement('select');select.setAttribute('aria-label','Endgame gear family');['balanced','cast','guard','status','hunt','harvest','dash'].forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=id.toUpperCase();select.appendChild(o);});select.value=K.Save.data.gearTarget||'balanced';select.addEventListener('change',()=>{K.Save.data.gearTarget=select.value;K.Save.write();updateModifierPreview();});target.appendChild(select);root.appendChild(target);}
  }
  function updateModifierPreview(){const p=K.Endgame?K.Endgame.modifierPreview(modifierRanks):{summary:'No modifiers selected',score:0};modifierRanks=Object.assign({},p.ranks||modifierRanks);by('modifier-preview').textContent=(p.summary||'Challenge '+p.score)+' · ENTRY COST: FREE · Ordinary run; no Trial ladder rewards.';K.Save.data.ordinaryModifiers=Object.assign({},modifierRanks);K.Save.write();}
  O.openMap=function(){if(!game.world)return;renderMap();screen('screen-world-map');};
  function renderMap(){
    const m=O.mapModel(game),w=game.world,b=m.bounds,s=m.tileSize,vx=b.x-s,vy=b.y-s,vw=b.w+s*2,vh=b.h+s*2;
    const colors={ground:'#a28a63',bridge:'#d6b579',water:'#417e89',wall:'#50463f',cliff:'#50463f',lava:'#b56842'};
    let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+[vx,vy,vw,vh].join(' ')+'" role="presentation">';
    m.cells.forEach(c=>{svg+='<rect x="'+(c.x-s/2)+'" y="'+(c.y-s/2)+'" width="'+s+'" height="'+s+'" fill="'+(colors[c.kind]||colors.ground)+'" opacity="'+(c.walkable?0.9:0.45)+'"/>';});
    m.markers.forEach(n=>{svg+='<circle cx="'+n.x+'" cy="'+n.y+'" r="'+(n.type==='boss'?95:70)+'" fill="'+(n.status==='cleared'?'#8dbb90':n.type==='boss'?'#d95f44':'#efd6a0')+'"/><text x="'+n.x+'" y="'+(n.y-100)+'" text-anchor="middle" fill="#f4e8d3" font-family="Georgia" font-size="105">'+esc(n.type.toUpperCase())+'</text>';});
    if(m.player)svg+='<circle cx="'+m.player.x+'" cy="'+m.player.y+'" r="70" fill="#ffffff" stroke="#dfb668" stroke-width="24"/>';
    svg+='</svg>';by('world-map-drawing').innerHTML=svg;by('map-caption').textContent=(game.world.profile.name||game.region().name)+' · Seed '+game.run.seed+' · '+m.cells.length+' discovered terrain tiles';by('map-legend').textContent='WHITE: YOU · GOLD: KNOWN DESTINATION · GREEN: CLEARED · RED: CAPSTONE · Undiscovered routes stay hidden.';lastMapRevision=w.revealRevision;
  }
  O.market=function(){if(!game.marketReturn&&!game.world?.safe)return;const root=by('market-inventory');root.innerHTML='';const stock=game.interactables.filter(it=>it.kind==='shop'&&it.item);by('market-balance').textContent=game.run.obols+' OBOLS · '+stock.filter(it=>!it.used).length+' wares remaining';stock.forEach(it=>{const item=it.item,b=document.createElement('button');b.className='market-ware';b.disabled=!!it.used;b.innerHTML='<strong>'+esc(item.name||item.id||item.kind)+'</strong><span>'+esc(item.desc||'')+'</span><small>'+ (it.used?'PURCHASED':it.cost+' OBOLS')+'</small>';b.addEventListener('click',()=>{game.interact(it);if(game.phase==='reward')return;O.market();ui.updateHUD();});root.appendChild(b);});if(!stock.length)root.innerHTML='<p>No wares at this landing.</p>';screen('screen-market');};
  O.house=function(){const root=by('house-scenes');root.innerHTML='';const scenes=K.Mythology?.scenesFor({context:'house',chapter:K.Save.data.bestRegion||0,save:K.Save.data})||[];scenes.forEach(scene=>{const b=document.createElement('button');b.className='house-scene';b.innerHTML='<strong>'+esc(scene.title)+'</strong><span>'+esc(scene.intro)+'</span>';b.addEventListener('click',()=>game.beginMythScene(scene.id,{context:'house',chapter:K.Save.data.bestRegion||0}));root.appendChild(b);});if(!scenes.length)root.innerHTML='<p>The House has no new conversations yet. Meet its travelers along the roads.</p>';screen('screen-house');};
  O.mirror=function(root,refresh){
    if(!K.Endgame)return;const api=K.Endgame,branches=Object.values(api.BRANCHES||{}),nodes=Object.values(api.NODES||{});
    branches.forEach(branch=>{const section=document.createElement('section');section.className='mirror-branch';section.innerHTML='<h3>'+esc(branch.name||branch.id)+'</h3><p>'+esc(branch.desc||branch.description||'')+'</p>';nodes.filter(n=>n.branch===branch.id).forEach(node=>{const p=api.branchPreview(node.id,K.Save.data),b=document.createElement('button');b.className='mirror-branch-node';b.disabled=!p.ok;b.innerHTML='<strong>'+esc(node.name)+'</strong><span>'+esc(node.desc||node.description)+'</span><small>'+esc(p.owned?'WOVEN':p.ok?p.cost+' OBOLS':p.reason)+'</small>';b.addEventListener('click',()=>{api.buyBranch(node.id);refresh();});section.appendChild(b);});root.appendChild(section);});
    const p=api.refundPreview('all',K.Save.data),respec=document.createElement('button');respec.className='btn ghostly';const canRespec=!!(p.ok||p.obols||p.refund);respec.textContent=canRespec?('RESPEC NEW BRANCHES · REFUND '+(p.obols||p.refund||p.refunded||0)+' OBOLS'):'RESPEC NEW BRANCHES · NOTHING TO REFUND';respec.disabled=!canRespec;if(!canRespec)respec.title='No branch purchases to refund yet.';respec.addEventListener('click',()=>{api.refundBranches('all');refresh();});root.appendChild(respec);const info=document.createElement('p');info.className='overhaul-intro';info.textContent='Branch respec refunds recorded purchases and preserves the original Mirror ranks, gear and campaign. DISSOLVE THE MIRROR remains the separate full reset.';root.appendChild(info);
  };
  function cost(p){return(p.cost?.obols||0)+' Obols · '+(p.cost?.shards||0)+' shards';}
  function effectPreview(p){if(!p)return'';const before=p.beforeStats||p.before||{},after=p.afterStats||p.after||{};return Object.keys(after).filter(k=>typeof after[k]==='number'&&after[k]!==before[k]).slice(0,12).map(k=>k.replace(/([A-Z])/g,' $1')+': '+Number(before[k]||0).toFixed(2)+' → '+Number(after[k]).toFixed(2)).join(' · ')||'Changes a conditional build interaction within the global caps.';}
  O.workbench=function(item){
    let host=by('armory-workbench');if(!host){host=document.createElement('div');host.id='armory-workbench';host.className='armory-workbench';by('armory-details').parentNode.appendChild(host);}host.innerHTML='';if(!item||!K.Gear.masterworkPreview)return;
    const gear=K.Gear,heading=document.createElement('h4');heading.textContent='THE WORKBENCH';host.appendChild(heading);
    const reinforcement=gear.reinforcementPreview(item.id),summary=document.createElement('p');summary.className='workbench-preview';summary.textContent='Reinforcement · '+(reinforcement.ok?cost(reinforcement)+' · '+effectPreview(reinforcement):reinforcement.reason);host.appendChild(summary);
    const focuses=gear.focuses(item),label=document.createElement('label');label.textContent='Masterwork focus';const select=document.createElement('select');select.setAttribute('aria-label','Masterwork focus');focuses.forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.name;select.appendChild(o);});select.value=item.masterworkFocus||focuses[0]?.id||'';label.appendChild(select);host.appendChild(label);
    const preview=document.createElement('p');preview.className='workbench-preview';preview.setAttribute('role','status');host.appendChild(preview);
    const action=document.createElement('button');action.className='btn small';action.textContent='MASTERWORK · '+(item.masterworkRanks||0)+'/3';host.appendChild(action);
    function update(){const p=gear.masterworkPreview(item.id,select.value);preview.textContent=(p.ok?cost(p):p.reason)+' · '+effectPreview(p)+(p.ranks?' · '+p.ranks.map((rank,i)=>'Rank '+(i+1)+': '+effectPreview(rank)).join(' / '):'');action.disabled=!p.ok;}
    select.addEventListener('change',update);update();action.addEventListener('click',()=>{gear.masterwork(item.id,select.value);ui.renderArmory();});
    const reset=gear.resetMasterworkPreview(item.id),rb=document.createElement('button');rb.className='btn small ghostly';rb.disabled=!reset.ok;rb.textContent='RESET FOCUS · '+cost(reset);rb.title=reset.reason||'Resets Masterwork only; item and affixes are preserved.';rb.addEventListener('click',()=>{gear.resetMasterwork(item.id);ui.renderArmory();});host.appendChild(rb);
    if(item.mythicTrait){const p=document.createElement('p');p.textContent=(gear.TRAITS[item.mythicTrait]?.name||item.mythicTrait)+' · '+(gear.TRAITS[item.mythicTrait]?.desc||'');host.appendChild(p);}
    if(item.rarity==='godforged'){const l=document.createElement('label');l.textContent='Godforged imprint';const s=document.createElement('select');s.setAttribute('aria-label','Godforged imprint');(item.imprintOptions||[]).forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=gear.IMPRINTS[id]?.name||id;s.appendChild(o);});s.value=item.imprint||'';l.appendChild(s);host.appendChild(l);const b=document.createElement('button');b.className='btn small';b.textContent='CHOOSE IMPRINT';const p=document.createElement('p');const update=()=>{const v=gear.imprintPreview(item.id,s.value);b.disabled=!v.ok;p.textContent=(gear.IMPRINTS[s.value]?.desc||'')+' · '+(v.ok?cost(v):v.reason);};s.addEventListener('change',update);update();b.addEventListener('click',()=>{gear.selectImprint(item.id,s.value);ui.renderArmory();});host.appendChild(p);host.appendChild(b);}
    if(item.affixes.length){const field=document.createElement('label');field.textContent='Refine one ordinary affix';const old=document.createElement('select'),next=document.createElement('select');old.setAttribute('aria-label','Affix to refine');next.setAttribute('aria-label','Replacement affix');item.affixes.forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=a.name;old.appendChild(o);});(gear.AFFIXES||[]).filter(a=>!item.affixes.some(b=>b.id===a.id)).forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=a.name;next.appendChild(o);});field.appendChild(old);field.appendChild(next);host.appendChild(field);const p=document.createElement('p'),b=document.createElement('button');b.className='btn small ghostly';b.textContent='REFINE AFFIX';const update=()=>{const v=gear.refinementPreview(item.id,old.value,next.value);b.disabled=!v.ok;p.textContent=(v.ok?cost(v):v.reason)+' · '+effectPreview(v);};old.addEventListener('change',update);next.addEventListener('change',update);update();b.addEventListener('click',()=>{gear.refine(item.id,old.value,next.value);ui.renderArmory();});host.appendChild(p);host.appendChild(b);}
  };
  O.handleKeys=function(input,current){if(!game)return false;if(current==='screen-world-map'&&(input.hit('Escape'))){screen(null);ui.updateHUD();return true;}if(current==='screen-market'&&input.hit('Escape')){screen(null);ui.updateHUD();return true;}if(current==='screen-house'&&input.hit('Escape')){screen('screen-title');return true;}if(current==='screen-modifiers'&&input.hit('Escape')){screen('screen-heroes');return true;}if(current==='play'&&game.world?.safe&&input.hit('KeyB')){O.market();return true;}return false;};
  O.tick=function(G,current,dt){
    if(!dockEl)dockEl=by('exploration-tools');if(!dockEl)return;
    const showDock=!!(G.world&&G.player&&current==='play');
    if(dockEl.classList.contains('hidden')===showDock)dockEl.classList.toggle('hidden',!showDock);
    if(showDock){
      let cleared=0;const nodes=G.world.nodes;
      for(let i=0;i<nodes.length;i++)if(nodes[i].main&&nodes[i].status==='cleared')cleared++;
      const next=cleared<8?nodes.find(n=>n.main&&n.status!=='cleared'):null;
      const text=G.world.safe?'Safe landing · Approach Charon or browse the wares':G.activeEncounter&&G.activeEncounter.status==='active'?'Encounter active · Passage opens after victory':next?'Road to '+next.landmark+' · '+cleared+'/8 encounters cleared':'Capstone cleared · Choose your next crossing';
      if(text!==worldHudKey){if(!objectiveEl)objectiveEl=by('world-objective');if(objectiveEl)objectiveEl.textContent=text;worldHudKey=text;}
      if(!marketBtnEl)marketBtnEl=by('world-market-button');if(marketBtnEl){const hide=!G.world.safe;if(marketBtnEl.classList.contains('hidden')!==hide)marketBtnEl.classList.toggle('hidden',hide);}
      if(current==='screen-world-map'&&G.world.revealRevision!==lastMapRevision)renderMap();
    }
    portraitTimer+=dt;if(K.Portraits&&portraitTimer>0.25){K.Portraits.refresh?.();portraitTimer=0;}
    if(typeof navigator==='undefined'||!navigator.getGamepads)return;
    const now=(typeof performance!=='undefined'?performance.now():0);if(now-lastPadCheck<100)return;lastPadCheck=now;
    const pads=navigator.getGamepads();let pad=null;for(let i=0;i<pads.length;i++)if(pads[i]){pad=pads[i];break;}if(!pad){padHeld={};return;}lastPad+=dt;
    const down=i=>!!pad.buttons[i]?.pressed,edge=i=>down(i)&&!padHeld[i];
    if(current==='screen-market'||current==='screen-modifiers'||current==='screen-house'||current==='screen-world-map'){
      const host=by(current),items=Array.from(host.querySelectorAll('button:not([disabled]),select')).filter(e=>e.offsetParent!==null),active=items.indexOf(document.activeElement);if((edge(13)||pad.axes[1]>0.6&&lastPad>0.2)&&items.length){items[(active+1)%items.length].focus();lastPad=0;}if((edge(12)||pad.axes[1]<-0.6&&lastPad>0.2)&&items.length){items[(active+items.length-1)%items.length].focus();lastPad=0;}if(edge(0)&&document.activeElement?.click)document.activeElement.click();if(edge(1))screen(current==='screen-modifiers'?'screen-heroes':current==='screen-house'?'screen-title':null);
    }else if(current==='play'&&edge(8))O.openMap();pad.buttons.forEach((b,i)=>padHeld[i]=b.pressed);
  };
})();
